def welcome_message
  puts "Hello! Welcome to [insert some cool name here] Flights!"
end

def goodbye
  puts "Goodbye! Please check us out again!"
end

def enter_user
  puts "Please enter your name: "
  gets.chomp.downcase
end

def enter_email
  puts "Please enter your email address: "
  gets.chomp.downcase
end

def origin
  puts "Please enter your starting location: "
  gets.chomp.downcase
end

def destination
  puts "Please enter your destination: "
  gets.chomp.downcase
end

def date
  puts "What is your desired departure date? "
  gets.chomp.downcase
end

def select_flights
  #should probably split this up.
  puts "Would you like to save a flight? (Y/N)"
  answer = gets.chomp.downcase
  if answer == "y"
    puts "Please list the flight number(s) that you would like to save. If selecting multiple, please separate with a space."
    flights = gets.chomp.downcase
    flights_to_save = flights.split(" ").map{|n| n.to_i}
  elsif answer != "y" && answer != "n"
    puts "That was an incorrect response!"
    goodbye
  end
  #this method collects the flight numbers that the person would want to save - remember - here the flight numbers are actually just the list of flights in the array_of_flights generated by the parse_search_results method. To actually create trips, you will need to search the database on all of the attributes in each flight(by flight number).
end

def user_view_trips
  puts "Here are the flights that you have saved."
end

def ask_user_to_book_flight
  puts "Would you like to book a flight? Y/N"
  answer = gets.chomp.downcase

  if answer == "y"
    puts "Please list the number of the flight you would like to book. Please list just one flight."
    flight = gets.chomp.to_i
  elsif answer != "y"
    flight = 0
  end

end
